--INSERT DATA AND FOREIGN KEYS CONSTRAINTS
USE PRJ_ECOMMERCE;
-- Insert into the Accounts table
INSERT INTO Accounts (email, password, fullname, avatar_url, role) VALUES
('admin@admin.com', '1', 'Duy Thái', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719281172/PRJ_ECOMMERCE/opvfjoatonnnolkpvvuc.jpg', 'admin'),
('customer1@customer.com', '1', 'Bùi Quang Minh', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719279086/PRJ_ECOMMERCE/opvfjoatonnnolkpvvuc.jpg', 'customer'),
('customer2@customer.com', '1', 'Dương Thành Luân', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719279086/PRJ_ECOMMERCE/opvfjoatonnnolkpvvuc.jpg','customer'),
('admin', 'admin', 'Admin User', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719279086/PRJ_ECOMMERCE/opvfjoatonnnolkpvvuc.jpg', 'admin'),
('customer', 'customer', 'Customer User', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719279086/PRJ_ECOMMERCE/opvfjoatonnnolkpvvuc.jpg', 'customer'),
('thaiddhe176315@fpt.edu.vn', '1', 'EDU', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719279086/PRJ_ECOMMERCE/opvfjoatonnnolkpvvuc.jpg', 'admin'),
('daoduythai.business@gmail.com', '1', 'BUSINESS','https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719279086/PRJ_ECOMMERCE/opvfjoatonnnolkpvvuc.jpg', 'admin'),
('dduythai.ddt@gmail.com', '1', 'PERSONAL', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719279086/PRJ_ECOMMERCE/opvfjoatonnnolkpvvuc.jpg', 'admin');
GO

-- Insert categories into the Categories table
INSERT INTO Categories ([name], [description])
VALUES 
    ('Laptop', 'All kinds of laptops'),
    ('Smartphone', 'Latest smartphones'),
    ('Camera', 'Cameras and photography equipment'),
    ('Accessories', 'Various electronic accessories');
GO

-- Insert into the Products table
INSERT INTO Products ([name], image_url, price, category_id, [description])
VALUES
    ('Dell XPS 13', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719281513/PRJ_ECOMMERCE/raoxw0bwfm70assnenhz.png', 30000000, 1, 'The Dell XPS 13 is a high-performance laptop designed for professionals and power users. It features a sleek, compact design with a virtually borderless InfinityEdge display, providing an immersive viewing experience. The laptop is powered by the latest Intel processors, ensuring fast and efficient performance for multitasking, productivity, and entertainment. It also includes advanced cooling technology to keep the system running smoothly under heavy loads. With a premium build quality, long battery life, and a stunning display, the Dell XPS 13 is perfect for those who demand the best in a portable device.'),
    ('MacBook Pro 16', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719281619/PRJ_ECOMMERCE/mkae7tm61dwqi1axoxjb.png', 60000000, 1, 'The MacBook Pro 16 is Apples most powerful laptop, featuring the revolutionary M1 chip that delivers incredible performance and efficiency. This laptop is designed for creative professionals, offering a stunning 16-inch Retina display with True Tone technology, providing accurate colors and deep blacks. It includes a Magic Keyboard with a refined scissor mechanism for a responsive, comfortable typing experience. The MacBook Pro 16 also boasts an advanced thermal design to sustain its pro-level performance. With up to 64GB of RAM, 8TB of storage, and up to 20 hours of battery life, it is ideal for intensive tasks like video editing, software development, and graphic design.'),
    ('HP Spectre x360', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719281813/PRJ_ECOMMERCE/l5r2rkp33ifqf2sijb2h.png', 45000000, 1, 'The HP Spectre x360 is a versatile convertible laptop with a touch screen that combines power, portability, and premium design. It features a 360-degree hinge that allows you to use it in multiple modes: laptop, tablet, stand, and tent. The Spectre x360 is powered by the latest Intel Core processors and includes an integrated Intel Iris Xe graphics card, making it perfect for both work and play. Its stunning 4K OLED display provides vibrant visuals, while the all-day battery life ensures you can stay productive on the go. The Spectre x360 also includes advanced security features such as a fingerprint reader and an IR camera for facial recognition.'),
    ('Asus ZenBook 14', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719281904/PRJ_ECOMMERCE/mtmu33mnyikk0386vyfh.png', 35000000, 1, 'The Dell XPS 13 is a high-performance laptop designed for professionals and power users. It features a sleek, compact design with a virtually borderless InfinityEdge display, providing an immersive viewing experience. The laptop is powered by the latest Intel processors, ensuring fast and efficient performance for multitasking, productivity, and entertainment. It also includes advanced cooling technology to keep the system running smoothly under heavy loads. With a premium build quality, long battery life, and a stunning display, the Dell XPS 13 is perfect for those who demand the best in a portable device.'),
    ('Lenovo ThinkPad X1', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719282051/PRJ_ECOMMERCE/hcp4dfcdi3wu6lmpzsik.png', 40000000, 1, 'The Lenovo ThinkPad X1 is a business laptop known for its robust features and durable design. It is equipped with powerful Intel processors, providing the performance needed for demanding business applications. The ThinkPad X1 features a stunning display with high resolution and vivid colors, perfect for detailed work. It also includes a responsive keyboard with the iconic TrackPoint, ensuring a comfortable typing experience. The laptop is designed to meet MIL-STD 810G standards for durability, making it resistant to drops, spills, and extreme temperatures. With advanced security features like a fingerprint reader and IR camera, the ThinkPad X1 ensures your data remains secure.'),
    ('Samsung Galaxy S21', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719282285/PRJ_ECOMMERCE/kupflujwkuoyb0zcksoe.png', 20000000, 2, 'The Samsung Galaxy S21 is a flagship smartphone that combines powerful features with a sleek design. It features a dynamic AMOLED 2X display with a 120Hz refresh rate, providing a smooth and immersive viewing experience. The Galaxy S21 is powered by the Exynos 2100 processor, ensuring fast and efficient performance for all your tasks. It includes a versatile triple-camera setup with advanced AI capabilities, allowing you to capture stunning photos and videos in any situation. The Galaxy S21 also offers 5G connectivity, a long-lasting battery, and support for fast charging, wireless charging, and reverse wireless charging.'),
    ('iPhone 13 Pro', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719282372/PRJ_ECOMMERCE/r5j7a5drmzuortleycs6.png', 30000000, 2, 'The iPhone 13 Pro is Apples newest iPhone, featuring the powerful A15 Bionic chip that delivers unparalleled performance and efficiency. The device boasts a Super Retina XDR display with ProMotion technology, offering smooth scrolling and enhanced responsiveness. The iPhone 13 Pro includes a pro camera system with advanced computational photography capabilities, allowing you to capture professional-quality photos and videos. It supports 5G connectivity for faster downloads and streaming. With improved battery life, enhanced durability, and iOS 15 features, the iPhone 13 Pro is the ultimate smartphone for anyone looking for top-tier performance and innovation.'),
    ('Google Pixel 6', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719282467/PRJ_ECOMMERCE/keqnzxw6o4l71w5ofy0t.png', 18000000, 2, 'The Google Pixel 6 is Googles flagship smartphone, featuring the powerful Google Tensor chip designed specifically for Pixel. It offers an adaptive 6.4-inch display with a 90Hz refresh rate, providing a smooth and responsive user experience. The Pixel 6 includes a new advanced camera system with enhanced computational photography features, allowing you to capture stunning photos and videos in any lighting conditions. It also offers a long-lasting battery, 5G connectivity, and the latest Android 12 features. The Pixel 6s design is sleek and modern, with a unique camera bar that sets it apart from other smartphones.'),
    ('OnePlus 9 Pro', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719282500/PRJ_ECOMMERCE/vbpkd48nnczwuorvuhsk.png', 22000000, 2, 'The OnePlus 9 Pro is a high-performance smartphone that combines advanced technology with a sleek design. It features a Fluid AMOLED display with a 120Hz refresh rate, providing a smooth and immersive viewing experience. The OnePlus 9 Pro is powered by the Snapdragon 888 processor, ensuring fast and efficient performance for all your tasks. It includes a Hasselblad quad-camera system with advanced color calibration and photography features, allowing you to capture stunning photos and videos. The device also offers fast charging, wireless charging, and 5G connectivity, making it perfect for users who demand the best from their smartphones.'),
    ('Sony Xperia 5 III', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719282542/PRJ_ECOMMERCE/drz0rtmjuyluvyhigoku.png', 15000000, 2, 'The Sony Xperia 5 III is a compact smartphone that offers advanced features in a sleek and portable design. It features a 6.1-inch OLED display with a 120Hz refresh rate, providing a smooth and vibrant viewing experience. The Xperia 5 III is powered by the Snapdragon 888 processor, ensuring fast and efficient performance for all your tasks. It includes a triple-camera system with ZEISS optics and advanced photography features, allowing you to capture stunning photos and videos. The device also offers 5G connectivity, a long-lasting battery, and support for fast charging, making it perfect for users who want a powerful and compact smartphone.'),
    
    ('Canon EOS R5', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719282613/PRJ_ECOMMERCE/xplmikdrduhjwxm81mcr.png', 75000000, 3, 'The Canon EOS R5 is a professional mirrorless camera designed for photographers and videographers who demand the highest performance. It features a 45-megapixel full-frame sensor and DIGIC X image processor, delivering stunning image quality and fast performance. The EOS R5 offers 8K video recording, 4K at 120fps, and advanced autofocus with 1,053 AF points, making it ideal for capturing high-resolution photos and videos. The camera also includes in-body image stabilization, a high-resolution electronic viewfinder, and a vari-angle touchscreen for versatile shooting angles. With its robust build and advanced features, the Canon EOS R5 is perfect for professional use.'),
    ('Nikon Z7 II', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719282658/PRJ_ECOMMERCE/tvyflsvefar5mo4vlitu.png', 70000000, 3, 'The Nikon Z7 II is a full-frame mirrorless camera that offers exceptional image quality and performance. It features a 45.7-megapixel sensor and dual EXPEED 6 processors, providing fast processing speeds and superior image detail. The Z7 II includes a sophisticated autofocus system with 493 focus points, ensuring precise focus in any situation. It supports 4K UHD video recording and has dual card slots for added flexibility. The cameras robust build, weather sealing, and ergonomic design make it suitable for professional photographers who need a reliable and high-performing camera for various shooting conditions.'),
    ('Sony Alpha 1', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719282727/PRJ_ECOMMERCE/powtsywellrxpzlb5pbx.png', 85000000, 3, 'The Sony Alpha 1 is a high-end camera designed for professional photographers and videographers. It boasts a 50.1-megapixel full-frame sensor and the powerful BIONZ XR processor, offering exceptional image quality and high-speed performance. The Alpha 1 supports 8K video recording, 4K at 120fps, and has an advanced autofocus system with 759 phase-detection points. It also features 30fps continuous shooting, dual card slots, and a high-resolution electronic viewfinder. With its advanced capabilities and robust design, the Sony Alpha 1 is ideal for capturing high-resolution images and videos in any environment.'),
    ('Fujifilm X-T4', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719282782/PRJ_ECOMMERCE/shjqq3xgawyq9zn6ttzj.png', 40000000, 3, 'The Fujifilm X-T4 is a versatile mirrorless camera that excels in both photography and videography. It features a 26.1-megapixel APS-C sensor and X-Processor 4, delivering excellent image quality and fast performance. The X-T4 offers 4K video recording at 60fps, in-body image stabilization, and a vari-angle touchscreen for flexible shooting angles. Its advanced autofocus system ensures precise focus in various shooting conditions. The cameras retro design, robust build, and weather sealing make it a favorite among photographers who want a reliable and stylish camera for all situations.'),
    ('Panasonic Lumix GH5', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719282817/PRJ_ECOMMERCE/wdwmdmyigna6y333aia8.png', 35000000, 3, 'The Panasonic Lumix GH5 is a professional video camera designed for filmmakers and content creators. It features a 20.3-megapixel Micro Four Thirds sensor and Venus Engine processor, delivering high-quality video and stills. The GH5 supports 4K video recording at 60fps, 10-bit 4:2:2 internal recording, and advanced V-LogL for professional color grading. It also includes 5-axis in-body image stabilization, a high-resolution electronic viewfinder, and a fully articulated touchscreen for versatile shooting. With its robust build and professional video features, the Lumix GH5 is perfect for serious videographers and filmmakers.'),
    ('JBL Charge 4', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719282858/PRJ_ECOMMERCE/pjvsbmhkggmgddtewgo3.png', 3000000, 4, 'The JBL Charge 4 is a portable Bluetooth speaker that delivers powerful sound and long-lasting battery life. It features a durable, waterproof design, making it perfect for outdoor use. The Charge 4 offers up to 20 hours of playtime on a single charge and can also act as a power bank to charge your devices on the go. Its dual passive radiators provide deep bass, while the JBL Connect+ feature allows you to connect multiple JBL speakers for an amplified sound experience. Whether at the beach, park, or home, the JBL Charge 4 provides exceptional sound quality and portability.'),
    ('Apple AirPods Pro', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719283065/PRJ_ECOMMERCE/egjjafid2j98fci4c3lb.png', 7000000, 4, 'The Apple AirPods Pro are wireless earbuds that offer active noise cancellation and superior sound quality. They feature a customizable fit with three sizes of soft silicone tips, ensuring comfort and a secure fit. The AirPods Pro include a transparency mode that lets you hear the environment around you, making them perfect for everyday use. They offer up to 4.5 hours of listening time on a single charge, with the wireless charging case providing additional battery life. The AirPods Pro are also sweat and water-resistant, making them ideal for workouts and outdoor activities.'),
    ('Samsung Galaxy Buds Pro', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719283135/PRJ_ECOMMERCE/za0culr7mp1gfsnv9mit.png', 5000000, 4, 'The Samsung Galaxy Buds Pro are premium wireless earbuds that offer advanced audio features and noise cancellation. They feature an 11mm woofer and 6.5mm tweeter in each earbud, delivering rich, balanced sound. The Galaxy Buds Pro include intelligent active noise cancellation, allowing you to switch between noise-canceling and ambient sound modes. They offer up to 5 hours of playtime with noise cancellation on, and the charging case provides additional battery life. The earbuds are also water-resistant and have touch controls for easy operation. With their sleek design and powerful audio performance, the Galaxy Buds Pro are perfect for music lovers and professionals alike.'),
    ('Sony WH-1000XM4', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719283180/PRJ_ECOMMERCE/elbpaovd9yaiplas8izv.png', 9000000, 4, 'The Sony WH-1000XM4 are noise-canceling over-ear headphones that offer superior sound quality and comfort. They feature Sonys advanced noise-canceling technology, which blocks out ambient noise for an immersive listening experience. The headphones include 40mm drivers, delivering clear, balanced sound with deep bass. They offer up to 30 hours of battery life on a single charge and support quick charging for an additional 5 hours of playback with just 10 minutes of charging. The WH-1000XM4 also include touch controls, voice assistant compatibility, and adaptive sound control for a personalized listening experience.'),
    ('Anker PowerCore 10000', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719283231/PRJ_ECOMMERCE/vqd3wa1vdvdwumqzkkfb.png', 1000000, 4, 'The Anker PowerCore 10000 is a compact and portable power bank that provides reliable charging on the go. It features a 10,000mAh battery capacity, allowing you to charge your smartphone multiple times. The PowerCore 10000 includes PowerIQ and VoltageBoost technologies, ensuring fast and efficient charging for your devices. Its compact design makes it easy to carry in your bag or pocket, and the high-quality construction ensures durability. With built-in safety features such as surge protection and short circuit prevention, the Anker PowerCore 10000 is a dependable power source for your mobile devices.'),
    
    ('Microsoft Surface 4', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719283324/PRJ_ECOMMERCE/svq7ahby8o1omrm9yvkv.png', 40000000, 1, 'The Microsoft Surface Laptop 4 is a sleek and powerful laptop designed for productivity and entertainment. It features a stunning 13.5-inch or 15-inch PixelSense touchscreen display, providing vibrant colors and sharp details. The laptop is equipped with the latest Intel or AMD processors, offering excellent performance for multitasking, creative work, and gaming. With up to 32GB of RAM and 1TB of SSD storage, it ensures smooth operation and ample storage space. The Surface Laptop 4 also boasts an elegant design, long battery life, and high-quality speakers, making it an ideal choice for professionals and students alike.'),
    ('Acer Predator Helios 300', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719283373/PRJ_ECOMMERCE/glofw4a3xp2n5jtt503m.png', 45000000, 1, 'The Acer Predator Helios 300 is a gaming laptop that delivers high performance and immersive gaming experiences. It features a 15.6-inch Full HD display with a high refresh rate of up to 144Hz, ensuring smooth and responsive gameplay. Powered by Intels latest processors and NVIDIA GeForce RTX graphics, the Helios 300 can handle the most demanding games and applications. The laptop includes 16GB of RAM, a 512GB SSD, and advanced cooling technology to keep the system running smoothly during intense gaming sessions. With its aggressive design and RGB-backlit keyboard, the Predator Helios 300 is perfect for gamers seeking a powerful and stylish laptop.'),
    ('Xiaomi Mi 11', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719283458/PRJ_ECOMMERCE/w66aiv3zwriqh5vzrpd3.png', 12000000, 2, 'The Xiaomi Mi 11 is an affordable smartphone packed with flagship features. It boasts a stunning 6.81-inch AMOLED display with a 120Hz refresh rate and HDR10+ support, providing a vibrant and smooth viewing experience. The Mi 11 is powered by the Qualcomm Snapdragon 888 processor, ensuring fast and efficient performance. It features a versatile triple-camera setup, including a 108MP main sensor, allowing you to capture high-quality photos and videos. The smartphone also includes a large battery with fast charging capabilities, an in-display fingerprint sensor, and a sleek design, making it a great choice for budget-conscious consumers looking for high-end features.'),
    ('Huawei P40 Pro', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719302259/PRJ_ECOMMERCE/mv4rcer069wa6ndcrmec.png', 20000000, 2, 'The Huawei P40 Pro is a flagship smartphone known for its excellent camera capabilities. It features a 6.58-inch OLED display with a 90Hz refresh rate, providing smooth visuals and vibrant colors. The P40 Pro is equipped with the Kirin 990 5G processor, delivering powerful performance and 5G connectivity. Its quad-camera system, co-engineered with Leica, includes a 50MP main sensor, a 40MP ultra-wide sensor, a 12MP telephoto sensor, and a TOF 3D depth sensor, allowing you to capture stunning photos and videos in any lighting condition. The smartphone also offers a large battery, fast charging, and an elegant design, making it ideal for photography enthusiasts and tech-savvy users.'),
    ('Olympus OM-D E-M1 Mark III', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719302319/PRJ_ECOMMERCE/o9lozlbcgwkyqzthm4cc.png', 50000000, 3, 'The Olympus OM-D E-M1 Mark III is a Micro Four Thirds camera designed for professional photographers. It features a 20.4-megapixel sensor and the TruePic IX image processor, delivering high-resolution images and fast performance. The E-M1 Mark III includes advanced image stabilization, allowing for sharp handheld shots even in low light. It supports 4K video recording, high-speed shooting up to 60fps, and an advanced autofocus system with 121 phase-detection points. The cameras rugged, weather-sealed body makes it suitable for various shooting environments, and its compact size ensures portability. With its professional-grade features and versatility, the OM-D E-M1 Mark III is perfect for capturing high-quality photos and videos.'),
    ('GoPro HERO9 Black', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719302454/PRJ_ECOMMERCE/pirilbpxqzg9ckxvwtgj.png', 10000000, 3, 'The GoPro HERO9 Black is an action camera designed for adventure enthusiasts. It features a 23.6-megapixel sensor, allowing you to capture stunning 5K videos and 20MP photos. The HERO9 Black includes HyperSmooth 3.0 stabilization, ensuring smooth and stable footage even in the most extreme conditions. The camera also offers a front-facing display for easy framing, a large rear touchscreen, and a durable, waterproof design up to 33 feet (10 meters). With advanced features such as TimeWarp 3.0, LiveBurst, and voice control, the GoPro HERO9 Black is perfect for capturing your adventures in high-quality detail.'),
    ('Bose QuietComfort 35 II', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719302510/PRJ_ECOMMERCE/vhyjo1nejli9q3diodu8.png', 8000000, 4, 'The Bose QuietComfort 35 II are wireless headphones that offer industry-leading noise cancellation and premium sound quality. They feature Boses advanced noise-canceling technology, which blocks out unwanted noise for a more immersive listening experience. The QuietComfort 35 II includes high-quality audio drivers, providing clear and balanced sound. They offer up to 20 hours of battery life on a single charge and support quick charging for an additional 2.5 hours of playback with just 15 minutes of charging. The headphones are also compatible with voice assistants such as Google Assistant and Amazon Alexa, allowing for hands-free control. With their comfortable design and superior audio performance, the QuietComfort 35 II are perfect for music lovers and frequent travelers.'),
    ('Logitech MX Master 3', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719302550/PRJ_ECOMMERCE/ckhwzw10h816xk81azb3.png', 3000000, 4, 'The Logitech MX Master 3 is an advanced wireless mouse designed for professionals. It features an ergonomic design, providing comfort and support for long hours of use. The MX Master 3 includes a high-precision 4,000 DPI sensor, ensuring smooth and accurate tracking on any surface. It also offers customizable buttons and a unique MagSpeed scroll wheel, allowing for fast and precise scrolling. The mouse supports Logitech Flow, enabling seamless control across multiple computers, and has a rechargeable battery that lasts up to 70 days on a single charge. With its advanced features and premium build quality, the Logitech MX Master 3 is ideal for productivity and creative work.'),
    ('Razer BlackWidow V3', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719302650/PRJ_ECOMMERCE/oqdfbyocszf5izowml7c.png', 4000000, 4, 'The Razer BlackWidow V3 is a mechanical gaming keyboard designed for gamers who demand precision and performance. It features Razers Green mechanical switches, providing a tactile and clicky feel with each keystroke. The BlackWidow V3 includes customizable RGB lighting with Razer Chroma, allowing you to personalize the keyboards appearance with millions of colors and effects. It also offers programmable macro keys, a durable aluminum frame, and a comfortable wrist rest for extended gaming sessions. With its responsive switches and advanced features, the Razer BlackWidow V3 is perfect for competitive gaming and everyday use.'),
    ('Motorola Edge Plus', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719302685/PRJ_ECOMMERCE/dgtd0533ltub1sv3jruc.png', 22000000, 2, 'The Motorola Edge Plus is a high-end smartphone that features a stunning curved display and powerful performance. It boasts a 6.7-inch OLED display with a 90Hz refresh rate, providing smooth and immersive visuals. The Edge Plus is powered by the Qualcomm Snapdragon 865 processor, ensuring fast and efficient performance. It includes a versatile triple-camera system with a 108MP main sensor, allowing you to capture detailed and vibrant photos. The smartphone also offers a large battery with fast charging capabilities, stereo speakers, and 5G connectivity. With its premium design and advanced features, the Motorola Edge Plus is ideal for users seeking a top-tier smartphone experience.'),
    
    ('Fitbit Charge 4', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719302761/PRJ_ECOMMERCE/zvmmuvbpjenawzwapenq.png', 3000000, 4, 'The Fitbit Charge 4 is a fitness tracker designed to help you stay active and healthy. It features built-in GPS to track your outdoor activities, including running, cycling, and hiking, without needing your phone. The Charge 4 monitors your heart rate, sleep patterns, and provides personalized insights into your fitness levels. With up to 7 days of battery life, you can wear it continuously without frequent recharging. The tracker also includes features like Spotify control, smartphone notifications, and contactless payments via Fitbit Pay. Its sleek and lightweight design makes it comfortable to wear all day.'),
	('Alienware m15 R6', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719302808/PRJ_ECOMMERCE/lvoc1fupyjlr4lworc5m.png', 50000000, 1, 'The Alienware m15 R6 is a high-end gaming laptop from Alienware, known for its premium build quality and powerful performance. It features a 15.6-inch QHD display with a 240Hz refresh rate, providing smooth and immersive visuals for gaming. Powered by Intels latest processors and NVIDIA GeForce RTX 30-series graphics, the m15 R6 can handle the most demanding games and applications with ease. It includes up to 32GB of RAM and 2TB of SSD storage, ensuring fast load times and ample space for your game library. The laptops advanced cooling system keeps it running efficiently during intense gaming sessions, and its customizable RGB lighting adds a touch of style.'),
    ('Asus ROG Zephyrus G14', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719302844/PRJ_ECOMMERCE/ghpvihee94oog2v53stv.png', 40000000, 1, 'The Asus ROG Zephyrus G14 is a compact gaming laptop that packs powerful specs into a portable design. It features a 14-inch QHD display with a 120Hz refresh rate, delivering sharp and fluid visuals. The G14 is powered by AMD Ryzen 9 processors and NVIDIA GeForce RTX 30-series graphics, providing excellent performance for gaming and creative tasks. It includes up to 32GB of RAM and 1TB of SSD storage, ensuring fast performance and plenty of storage space. The laptops innovative cooling system and long battery life make it ideal for gaming on the go, and its unique AniMe Matrix LED display on the lid adds a customizable and stylish touch.'),
    ('MSI GS66 Stealth', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719302937/PRJ_ECOMMERCE/lws01lzzrtnkn0ia7jjo.png', 45000000, 1, 'The MSI GS66 Stealth is a sleek and powerful gaming laptop designed for gamers and professionals. It features a 15.6-inch Full HD display with a 240Hz refresh rate, ensuring smooth and responsive gameplay. The GS66 Stealth is powered by Intels latest processors and NVIDIA GeForce RTX 30-series graphics, providing top-tier performance for gaming and content creation. It includes up to 32GB of RAM and 1TB of SSD storage, offering fast load times and ample storage space. The laptops advanced cooling technology ensures optimal performance during extended gaming sessions, and its slim, all-black design makes it a stylish and portable choice.'),
    ('Razer Blade 15', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719303033/PRJ_ECOMMERCE/pf6okc9jtquqngslmzgd.png', 55000000, 1, 'The Razer Blade 15 is a premium gaming laptop known for its sleek design and powerful performance. It features a 15.6-inch Full HD or QHD display with up to a 360Hz refresh rate, providing ultra-smooth visuals for gaming. The Blade 15 is powered by Intels latest processors and NVIDIA GeForce RTX 30-series graphics, ensuring exceptional performance for gaming, streaming, and creative work. It includes up to 32GB of RAM and 1TB of SSD storage, offering fast performance and ample storage capacity. The laptops thin and lightweight design, combined with customizable RGB lighting and an advanced cooling system, makes it an ideal choice for gamers seeking a high-performance, portable gaming laptop.'),
    ('Acer Swift 3', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719303136/PRJ_ECOMMERCE/mqqghh9xp2iupohnrlih.png', 20000000, 1, 'The Acer Swift 3 is an affordable and lightweight laptop designed for everyday use. It features a 14-inch Full HD display, providing clear and vibrant visuals. The Swift 3 is powered by AMD Ryzen or Intel Core processors, offering reliable performance for multitasking, web browsing, and media consumption. It includes up to 16GB of RAM and 512GB of SSD storage, ensuring fast load times and smooth operation. The laptops slim and lightweight design makes it highly portable, and its long battery life ensures you can stay productive throughout the day. With its combination of performance, portability, and affordability, the Acer Swift 3 is an excellent choice for students and professionals.'),
    ('Samsung Galaxy Note 20', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719303182/PRJ_ECOMMERCE/jwyrd7ozywuujsn6hxun.png', 28000000, 2, 'The Samsung Galaxy Note 20 Ultra is a high-end smartphone that offers powerful performance and a range of features designed for productivity and creativity. It features a 6.9-inch Dynamic AMOLED display with a 120Hz refresh rate, providing stunning visuals and smooth scrolling. The Note 20 Ultra is powered by the Exynos 990 or Qualcomm Snapdragon 865+ processor, ensuring fast and efficient performance. It includes a versatile triple-camera system, featuring a 108MP main sensor, a 12MP ultra-wide sensor, and a 12MP periscope telephoto sensor, allowing you to capture high-quality photos and videos. The smartphone also includes the S Pen, which offers precise control and a range of productivity features. With its large battery, 5G connectivity, and premium design, the Galaxy Note 20 Ultra is perfect for users seeking a top-tier smartphone experience.'),
    ('Oppo Find X3 Pro', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719303243/PRJ_ECOMMERCE/pmmwcihcuh3vvj2arx5r.png', 23000000, 2, 'The Oppo Find X3 Pro is a flagship smartphone that combines a unique design with advanced features. It features a 6.7-inch AMOLED display with a 120Hz refresh rate and HDR10+ support, providing stunning visuals and smooth performance. The Find X3 Pro is powered by the Qualcomm Snapdragon 888 processor, ensuring fast and efficient performance. It includes a quad-camera system with a 50MP main sensor, a 50MP ultra-wide sensor, a 13MP telephoto sensor, and a 3MP microlens, allowing you to capture detailed and versatile photos. The smartphone also offers a large battery with fast charging capabilities, 5G connectivity, and a sleek, curved design. With its combination of cutting-edge technology and stylish design, the Oppo Find X3 Pro is perfect for users seeking a premium smartphone experience.'),
    ('Vivo X60 Pro', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719303286/PRJ_ECOMMERCE/chkfkhmwg0hdh7z0hukb.png', 18000000, 2, 'The Vivo X60 Pro is a smartphone designed for photography enthusiasts, featuring advanced camera capabilities and powerful performance. It boasts a 6.56-inch AMOLED display with a 120Hz refresh rate, providing smooth and vibrant visuals. The X60 Pro is powered by the Qualcomm Snapdragon 870 processor, ensuring fast and efficient performance. It includes a triple-camera system with a 48MP main sensor, a 13MP ultra-wide sensor, and a 13MP telephoto sensor, co-engineered with ZEISS optics, delivering stunning photos and videos. The smartphone also offers a large battery with fast charging, 5G connectivity, and a sleek design. With its emphasis on camera performance and premium features, the Vivo X60 Pro is ideal for users who prioritize mobile photography.'),
    ('Sony Xperia 1 II', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719303328/PRJ_ECOMMERCE/beowc7allvontse39izx.png', 25000000, 2, 'The Sony Xperia 1 II is a flagship smartphone that offers a unique combination of advanced camera technology and a stunning display. It features a 6.5-inch 4K HDR OLED display with a 21:9 aspect ratio, providing an immersive viewing experience. The Xperia 1 II is powered by the Qualcomm Snapdragon 865 processor, ensuring fast and efficient performance. It includes a triple-camera system with three 12MP sensors, co-engineered with ZEISS optics, delivering professional-grade photos and videos. The smartphone also offers a large battery with fast charging, 5G connectivity, and a sleek, water-resistant design. With its emphasis on display quality and camera performance, the Sony Xperia 1 II is perfect for users seeking a high-end smartphone experience.'),
    
    ('Asus ROG Phone 5', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719303451/PRJ_ECOMMERCE/e56ygnpdrvpvkdhp0dor.png', 30000000, 2, 'The Asus ROG Phone 5 is a high-performance gaming smartphone equipped with advanced cooling technology. It features a 6.78-inch AMOLED display with a 144Hz refresh rate and 1ms response time, providing ultra-smooth and responsive gameplay. The phone is powered by the Qualcomm Snapdragon 888 processor, ensuring top-tier performance for gaming and multitasking. It includes up to 16GB of RAM and 512GB of storage, offering ample space for games and apps. The ROG Phone 5 also features AirTrigger 5 controls for an enhanced gaming experience, and its 6000mAh battery ensures long-lasting power. The devices innovative GameCool 5 cooling system keeps it running smoothly even during intense gaming sessions.'),
    ('Nikon D850', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719303501/PRJ_ECOMMERCE/w0atfa5a3ivxjl8umsc0.png', 60000000, 3, 'The Nikon D850 is a high-resolution DSLR camera designed for professional photographers. It features a 45.7MP full-frame CMOS sensor and EXPEED 5 image processor, delivering exceptional image quality and fast performance. The D850 offers a wide ISO range of 64-25600, allowing for great low-light performance. It also includes a 153-point AF system and 7 fps continuous shooting speed, making it ideal for capturing fast-moving subjects. The camera supports 4K UHD video recording and offers a range of advanced features, including focus stacking, time-lapse recording, and built-in Wi-Fi and Bluetooth connectivity. Its rugged build and weather sealing make it suitable for challenging environments.'),
    ('Canon EOS 90D', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719303531/PRJ_ECOMMERCE/ifseip9i6wokvivs2j5f.png', 35000000, 3, 'The Canon EOS 90D is a versatile DSLR camera aimed at photography enthusiasts. It features a 32.5MP APS-C CMOS sensor and DIGIC 8 image processor, delivering high-resolution images and fast performance. The 90D offers a 45-point all cross-type AF system and up to 10 fps continuous shooting speed, making it suitable for sports and wildlife photography. It supports 4K UHD video recording and includes a vari-angle touchscreen LCD for flexible shooting angles. The camera also offers built-in Wi-Fi and Bluetooth connectivity, allowing for easy sharing and remote control. With its solid build and advanced features, the EOS 90D is perfect for capturing high-quality photos and videos in various situations.'),
    ('Sony A7 III', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719303592/PRJ_ECOMMERCE/ng089mbneuxutgyekkxn.png', 45000000, 3, 'The Sony A7 III is a full-frame mirrorless camera that offers excellent features for both photography and videography. It features a 24.2MP BSI full-frame sensor and BIONZ X image processor, providing outstanding image quality and low-light performance. The A7 III includes a 693-point AF system and up to 10 fps continuous shooting speed, making it ideal for capturing fast action. It supports 4K UHD video recording with full pixel readout and no pixel binning, ensuring high-quality video capture. The camera also offers 5-axis in-body image stabilization, dual SD card slots, and a long battery life. With its compact and durable design, the A7 III is perfect for professional and enthusiast photographers alike.'),
    ('Fujifilm X100V', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719303625/PRJ_ECOMMERCE/a9rd1nkkvyaglfjv5fwe.png', 30000000, 3, 'The Fujifilm X100V is a compact camera that features a hybrid viewfinder and is perfect for street photography. It includes a 26.1MP APS-C X-Trans CMOS 4 sensor and X-Processor 4, delivering high-quality images with rich colors. The X100V offers a fixed 23mm f/2 lens, providing a classic 35mm equivalent focal length. It also includes an advanced hybrid viewfinder, allowing you to switch between an optical and electronic viewfinder. The camera supports 4K video recording at 30 fps and offers various film simulation modes to enhance your creativity. Its sleek, retro design and robust build make it a stylish and reliable choice for photographers.'),
    ('Panasonic Lumix S5', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719303681/PRJ_ECOMMERCE/iassmwc504triqin8kkl.png', 55000000, 3, 'The Panasonic Lumix S5 is a full-frame mirrorless camera designed for both photographers and videographers. It features a 24.2MP full-frame CMOS sensor and Venus Engine, delivering high-quality images and excellent low-light performance. The S5 includes a 5-axis Dual I.S. 2 image stabilization system, providing up to 6.5 stops of stabilization for handheld shooting. It supports 4K UHD video recording at 60p with 10-bit internal recording, making it ideal for professional video work. The camera also offers V-Log and HDR recording, along with dual SD card slots for extended storage. Its compact and lightweight design, combined with its advanced features, make the Lumix S5 a versatile and powerful camera.'),
    ('Beats Solo Pro', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719303890/PRJ_ECOMMERCE/wt4jhcihncxdqhf9oxkh.png', 7000000, 4, 'The Beats Solo Pro are wireless noise-cancelling headphones designed for immersive sound and all-day comfort. They feature advanced noise-cancellation technology, allowing you to block out external noise and focus on your music. The headphones offer up to 22 hours of battery life with noise-cancellation on, and up to 40 hours with it off. The Solo Pro includes the Apple H1 chip, ensuring a seamless and stable wireless connection with Apple devices. They also feature transparency mode, allowing you to hear your surroundings when needed. With their sleek design and premium build quality, the Beats Solo Pro are perfect for music lovers who want high-quality sound and comfort.'),
    ('Bose SoundLink Revolve', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719303939/PRJ_ECOMMERCE/ml0wp0z7aqqobgoh63bu.png', 6000000, 4, 'The Bose SoundLink Revolve is a portable Bluetooth speaker that delivers 360-degree sound for a consistent and immersive listening experience. It features a durable, water-resistant design, making it ideal for outdoor use. The speaker offers up to 12 hours of battery life, ensuring you can enjoy your music all day long. The SoundLink Revolve includes a built-in microphone for speakerphone calls and voice assistant access, making it a versatile choice for both music and communication. With its compact size and powerful sound, the Bose SoundLink Revolve is perfect for music lovers who want a portable and high-quality speaker.'),
    ('Amazon Echo Dot', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719304381/PRJ_ECOMMERCE/gdmqmwhydo5tsq9tplmv.png', 2000000, 4, 'The Amazon Echo Dot is a smart speaker with Alexa, offering a range of voice-controlled features. It features a compact design and delivers crisp, clear sound for music, audiobooks, and more. The Echo Dot allows you to control your smart home devices, set alarms and timers, check the weather, and get news updates, all with simple voice commands. It also supports multi-room audio, allowing you to connect multiple Echo devices for synchronized music playback throughout your home. With its affordable price and versatile functionality, the Amazon Echo Dot is perfect for anyone looking to add smart home capabilities to their living space.'),
    ('Google Nest Hub', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719304454/PRJ_ECOMMERCE/anirlzzwublpvy8zcphb.png', 4000000, 4, 'The Google Nest Hub is a smart display with Google Assistant, providing hands-free help at a glance. It features a 7-inch touchscreen display, allowing you to view photos, watch videos, and control your smart home devices. The Nest Hub offers voice control for music and video streaming, along with personalized routines to help you start and end your day. It also includes a built-in speaker and microphone for clear audio and voice recognition. With its sleek design and intuitive interface, the Google Nest Hub is perfect for enhancing your smart home experience.'),
    
    ('Apple Watch Series 6', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719304490/PRJ_ECOMMERCE/bql6lg32slxbw9ayvh7u.png', 12000000, 4, 'The Apple Watch Series 6 is a premium smartwatch equipped with advanced health tracking features. It includes a blood oxygen sensor and ECG app, allowing you to monitor your heart health. The watch features an always-on Retina display, ensuring you can see important information at a glance. It also offers sleep tracking, fitness tracking, and a variety of workout modes. The Series 6 supports Apple Pay for contactless payments and includes built-in GPS. With its sleek design and comprehensive health features, the Apple Watch Series 6 is an excellent choice for those looking to stay connected and maintain a healthy lifestyle.'),
    ('Microsoft Surface Pro 7', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719304631/PRJ_ECOMMERCE/b1hopsrvrqtz9x1dqbjz.png', 35000000, 1, 'The Microsoft Surface Pro 7 is a versatile 2-in-1 laptop with a detachable keyboard, allowing you to switch between laptop and tablet modes. It features a 12.3-inch PixelSense display with a high resolution and responsive touch capabilities. The Surface Pro 7 is powered by 10th Gen Intel Core processors, ensuring strong performance for multitasking and productivity. It includes up to 16GB of RAM and up to 1TB of SSD storage, offering ample space for your files and applications. The device also supports the Surface Pen for enhanced creativity and note-taking. With its lightweight design and powerful features, the Surface Pro 7 is ideal for professionals and students alike.'),
    ('HP Envy x360', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719304724/PRJ_ECOMMERCE/wjusy5yxd1kwghhs6fdl.png', 30000000, 1, 'The HP Envy x360 is a convertible laptop featuring a touch screen and a flexible hinge, allowing you to use it in various modes. It includes a 15.6-inch Full HD display with vibrant colors and crisp details. The Envy x360 is powered by AMD Ryzen processors, delivering strong performance for everyday tasks and multimedia. It offers up to 16GB of RAM and up to 512GB of SSD storage, providing fast and efficient operation. The laptop also features a backlit keyboard, Bang & Olufsen audio, and a sleek, durable design. With its versatility and robust features, the HP Envy x360 is perfect for both work and entertainment.'),
    ('Lenovo Legion 5', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719304769/PRJ_ECOMMERCE/cttzblx4dsvowf49byud.png', 40000000, 1, 'The Lenovo Legion 5 is a gaming laptop known for its powerful performance and sleek design. It features a 15.6-inch Full HD display with a high refresh rate, ensuring smooth and immersive gaming experiences. The Legion 5 is powered by AMD Ryzen processors and NVIDIA GeForce GTX or RTX graphics, delivering high performance for demanding games and applications. It includes up to 16GB of RAM and up to 1TB of SSD storage, offering ample space and fast load times. The laptop also features a backlit keyboard, advanced cooling system, and robust build quality. With its powerful specs and gamer-centric features, the Lenovo Legion 5 is an excellent choice for gaming enthusiasts.'),
    ('Dell Inspiron 15', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719305159/PRJ_ECOMMERCE/gl2n6ozbrell6g7a9tsi.png', 20000000, 1, 'The Dell Inspiron 15 is an affordable laptop designed for everyday use. It features a 15.6-inch Full HD display, providing clear and detailed visuals for work and entertainment. The Inspiron 15 is powered by Intel Core processors, ensuring reliable performance for daily tasks. It includes up to 8GB of RAM and up to 512GB of SSD storage, offering sufficient space and quick access to your files and applications. The laptop also features a comfortable keyboard, long battery life, and a lightweight design. With its balance of performance and affordability, the Dell Inspiron 15 is perfect for students and professionals seeking a reliable laptop for daily use.'),
    ('Huawei MateBook X Pro', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719305943/PRJ_ECOMMERCE/ozla4uuzrbnawxskmu2n.png', 35000000, 1, 'The Huawei MateBook X Pro is a sleek and powerful laptop designed for productivity and multimedia. It features a 13.9-inch 3K display with a high screen-to-body ratio, offering stunning visuals and an immersive viewing experience. The MateBook X Pro is powered by Intel Core processors, delivering strong performance for multitasking and creative work. It includes up to 16GB of RAM and up to 1TB of SSD storage, providing ample space and fast access to your data. The laptop also features a backlit keyboard, fingerprint sensor, and long battery life. With its premium design and robust features, the Huawei MateBook X Pro is an excellent choice for professionals and content creators.'),
    ('Realme GT', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719319643/PRJ_ECOMMERCE/ykwvemhz6oop2wlstmjn.png', 12000000, 2, 'The Realme GT is a flagship smartphone equipped with the powerful Snapdragon 888 processor. It features a 6.43-inch Super AMOLED display with a 120Hz refresh rate, providing smooth and vibrant visuals. The Realme GT includes up to 12GB of RAM and up to 256GB of storage, offering ample space and fast performance for gaming and multitasking. The phone also features a triple camera setup with a 64MP main sensor, delivering high-quality photos and videos. It includes a 4500mAh battery with 65W fast charging, ensuring you can quickly recharge and stay connected. With its premium features and competitive price, the Realme GT is an excellent choice for tech enthusiasts.'),
    ('Nokia 8.3 5G', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719306140/PRJ_ECOMMERCE/d4pls922trv5zjhvuf1x.png', 15000000, 2, 'The Nokia 8.3 5G is a smartphone featuring advanced camera technology and 5G connectivity. It includes a 6.81-inch PureDisplay, offering clear and vibrant visuals. The phone is powered by the Qualcomm Snapdragon 765G processor, ensuring smooth performance for everyday tasks and 5G capabilities. The Nokia 8.3 5G features a quad-camera setup with ZEISS optics, including a 64MP main sensor, providing excellent photo and video quality. It also includes a large 4500mAh battery, ensuring long-lasting usage. With its robust features and 5G connectivity, the Nokia 8.3 5G is a great choice for those seeking a future-proof smartphone.'),
    ('Xiaomi Redmi Note 10 Pro', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719306194/PRJ_ECOMMERCE/ffhnmkww0xkqtpslmjaj.png', 9000000, 2, 'The Xiaomi Redmi Note 10 Pro is an affordable smartphone offering great features and performance. It includes a 6.67-inch Super AMOLED display with a 120Hz refresh rate, providing smooth and vibrant visuals. The phone is powered by the Qualcomm Snapdragon 732G processor, ensuring reliable performance for everyday tasks. The Redmi Note 10 Pro features a quad-camera setup with a 108MP main sensor, delivering high-quality photos and videos. It also includes a large 5020mAh battery with 33W fast charging, ensuring you can stay connected throughout the day. With its impressive features and budget-friendly price, the Xiaomi Redmi Note 10 Pro is an excellent choice for those seeking value for money.'),
    ('Vivo V21', 'https://res.cloudinary.com/dmqd2y3mp/image/upload/v1719306254/PRJ_ECOMMERCE/unpa25wxfgra9h1hi7c2.png', 10000000, 2, 'The Vivo V21 is a mid-range smartphone featuring 5G support and advanced camera capabilities. It includes a 6.44-inch AMOLED display with a high refresh rate, providing vibrant and smooth visuals. The phone is powered by the MediaTek Dimensity 800U processor, ensuring strong performance for multitasking and 5G connectivity. The Vivo V21 features a triple camera setup with a 64MP main sensor, delivering excellent photo and video quality. It also includes a 4000mAh battery with 33W fast charging, ensuring you can quickly recharge and stay connected. With its sleek design and robust features, the Vivo V21 is a great choice for those seeking a mid-range 5G smartphone.');
GO

-- Insert into the Orders table
INSERT INTO Orders (account_id, total_price, delivery_address, receiver_name, receiver_phone, [status], note)
VALUES
    (2, 262000000, '123 Main Street, Hanoi', 'codewithdt', '+84 79 6428 094', 'Processing', 'Please deliver during weekdays.'),
    (3, 234000000, '456 Nguyen Hue Street, Ho Chi Minh City', 'codewithdt', '+84 79 6428 094', 'Shipped', 'Delivery expected by end of week.'),
    (5, 117000000, '789 Tran Hung Dao Avenue, Da Nang', 'codewithdt', '+84 79 6428 094', 'Processing', 'Contact recipient before delivery.'),
    (6, 167000000, '567 Le Loi Boulevard, Hue', 'codewithdt', '+84 79 6428 094', 'Delivered', 'Left at front door.'),
    (7, 310000000, '999 Phan Chu Trinh Street, Nha Trang', 'codewithdt', '+84 79 6428 094', 'Processing', 'Handle with care.'),
    (5, 350000000, '888 Nguyen Trai Road, Can Tho', 'codewithdt', '+84 79 6428 094', 'Shipped', 'Delivery instructions included.'),
    (6, 270000000, '222 Ly Thai To Street, Hai Phong', 'codewithdt', '+84 79 6428 094', 'Processing', 'Contact recipient.'),
    (5, 68000000, '333 Vo Van Tan Street, Vung Tau', 'codewithdt', '+84 79 6428 094', 'Delivered', 'Signed by recipient.'),
    (6, 66000000, '444 Nguyen Dinh Chieu Road, Quy Nhon', 'codewithdt', '+84 79 6428 094', 'Processing', 'Call before delivery.'),
    (6, 116000000, '555 Tran Phu Street, Phu Quoc', 'codewithdt', '+84 79 6428 094', 'Shipped', 'Handle with care.'),
    (5, 85000000, '666 Dien Bien Phu Street, Buon Ma Thuot', 'codewithdt', '+84 79 6428 094', 'Processing', 'Call recipient on delivery.'),
    (2, 95000000, '777 Nguyen Van Linh Street, Can Gio', 'codewithdt', '+84 79 6428 094', 'Delivered', 'Left at gate.'),
    (5, 107000000, '111 Vo Thi Sau Avenue, Vung Tau', 'codewithdt', '+84 79 6428 094', 'Processing', 'Delivery expected today.'),
    (6, 61000000, '222 Ton Duc Thang Road, Ha Long', 'codewithdt', '+84 79 6428 094', 'Shipped', 'Contact recipient.'),
    (7, 150000000, '333 Le Duan Street, Rach Gia', 'codewithdt', '+84 79 6428 094', 'Processing', 'Leave at front desk.'),
    (2, 170000000, '444 Tran Quoc Toan Boulevard, Tam Ky', 'codewithdt', '+84 79 6428 094', 'Delivered', 'Signed by security.'),
    (5, 115000000, '555 Truong Sa Street, Con Dao', 'codewithdt', '+84 79 6428 094', 'Processing', 'Handle with care.'),
    (6, 27000000, '666 Nguyen Trai Avenue, Soc Trang', 'codewithdt', '+84 79 6428 094', 'Shipped', 'Delivery instructions included.'),
    (7, 8000000, '777 Tran Hung Dao Street, Long Xuyen', 'codewithdt', '+84 79 6428 094', 'Processing', 'Call recipient.'),
    (5, 24000000, '888 Ly Thuong Kiet Road, Dong Hoi', 'codewithdt', '+84 79 6428 094', 'Delivered', 'Left at front door.');
GO

-- Insert 40 order details
INSERT INTO Order_details (product_id, order_id, quantity, price)
VALUES
    (2, 1, 2, 60000000),    -- 2 units of MacBook Pro 16
    (3, 1, 1, 45000000),    -- 1 unit of HP Spectre x360
    (6, 1, 2, 20000000),    -- 2 units of Samsung Galaxy S21 
    (9, 1, 1, 22000000),    -- 1 unit of OnePlus 9 Pro
    (51, 1, 1, 35000000),  -- 1 unit of Microsoft Surface Pro 7 
    -- 60000000*2+45000000+20000000*2+22000000+35000000=262000000

    (4, 2, 1, 35000000),    -- 1 unit of Asus ZenBook 14
    (5, 2, 3, 40000000),    -- 3 units of Lenovo ThinkPad X1
    (12, 2, 1, 70000000),   -- 1 unit of Nikon Z7 II 
    (16, 2, 3, 3000000),    -- 3 units of JBL Charge 4 
    -- 35000000+40000000*3+70000000+3000000*3=234000000

    (6, 3, 2, 20000000),    -- 2 units of Samsung Galaxy S21
    (7, 3, 1, 30000000),    -- 1 unit of iPhone 13 Pro
    (20, 3, 2, 1000000),    -- 2 units of Anker PowerCore 10000 
    (34, 3, 1, 45000000),   -- 1 unit of MSI GS66 Stealth 
    -- 20000000*2+30000000+1000000*2+45000000=117000000

    (8, 4, 2, 18000000),    -- 2 units of Google Pixel 6
    (9, 4, 1, 22000000),    -- 1 unit of OnePlus 9 Pro
    (37, 4, 3, 28000000),   -- 3 units of Samsung Galaxy Note 20 Ultra 
    (40, 4, 1, 25000000),   -- 1 unit of Sony Xperia 1 II 
    -- 18000000*2+22000000+28000000*3+25000000=167000000

    (10, 5, 1, 15000000),    -- 1 unit of Sony Xperia 5 III
    (11, 5, 2, 75000000),   -- 2 units of Canon EOS R5
    (43, 5, 1, 35000000),   -- 1 unit of Canon EOS 90D 
    (46, 5, 2, 55000000),   -- 2 units of Panasonic Lumix S5 
    -- 15000000+75000000*2+35000000+55000000*2=310000000

    (12, 6, 1, 70000000),   -- 1 unit of Nikon Z7 II
    (13, 6, 3, 85000000),   -- 3 units of Sony Alpha 1
    (47, 6, 3, 7000000),    -- 3 units of Beats Solo Pro 
    (50, 6, 1, 4000000),    -- 1 unit of Google Nest Hub 
    -- 70000000+85000000*3+7000000*3+4000000=350000000

    (14, 7, 2, 40000000),   -- 2 units of Fujifilm X-T4
    (15, 7, 1, 35000000),   -- 1 unit of Panasonic Lumix GH5
    (2, 7, 2, 60000000),    -- 2 units of MacBook Pro 16 
    (4, 7, 1, 35000000),    -- 1 unit of Asus ZenBook 14 
    -- 40000000*2+35000000+60000000*2+35000000=270000000

    (16, 8, 3, 3000000),    -- 3 units of JBL Charge 4
    (17, 8, 2, 7000000),    -- 2 units of Apple AirPods Pro
    (18, 8, 1, 5000000),     -- 1 unit of Samsung Galaxy Buds Pro 
    (33, 8, 2, 40000000),   -- 2 units of Asus ROG Zephyrus G14 
    -- 3000000*3+7000000*2+5000000+40000000=68000000

    (18, 9, 1, 5000000),    -- 1 unit of Samsung Galaxy Buds Pro
    (19, 9, 2, 9000000),    -- 2 units of Sony WH-1000XM4
    (16, 9, 1, 3000000),    -- 1 unit of JBL Charge 4 
    (36, 9, 2, 20000000),   -- 2 units of Acer Swift 3 
    -- 5000000+9000000*2+3000000+20000000*2=66000000

    (20, 10, 3, 1000000),   -- 3 units of Anker PowerCore 10000
    (33, 10, 1, 50000000),  -- 1 unit of Alienware m15 R6
    (34, 10, 1, 45000000),   -- 1 unit of MSI GS66 Stealth 
    (19, 10, 2, 9000000),    -- 2 units of Sony WH-1000XM4 
    -- 1000000*3+50000000+45000000+9000000*2=116000000

    (33, 11, 2, 40000000),  -- 2 units of Asus ROG Zephyrus G14
    (34, 11, 1, 45000000),  -- 1 unit of MSI GS66 Stealth
    -- 40000000+45000000=85000000

    (35, 12, 1, 55000000),  -- 1 unit of Razer Blade 15
    (36, 12, 2, 20000000),  -- 2 units of Acer Swift 3
    -- 55000000+20000000*2=95000000

    (37, 13, 3, 28000000),  -- 3 units of Samsung Galaxy Note 20 Ultra
    (38, 13, 1, 23000000),  -- 1 unit of Oppo Find X3 Pro
    -- 28000000*3+23000000=107000000

    (39, 14, 2, 18000000),  -- 2 units of Vivo X60 Pro
    (40, 14, 1, 25000000),  -- 1 unit of Sony Xperia 1 II
    -- 18000000*2+25000000=61000000

    (41, 15, 1, 30000000),  -- 1 unit of Asus ROG Phone 5
    (42, 15, 2, 60000000),  -- 2 units of Nikon D850
    -- 30000000+60000000*2=150000000

    (43, 16, 1, 35000000),  -- 1 unit of Canon EOS 90D
    (44, 16, 3, 45000000),  -- 3 units of Sony A7 III
    -- 35000000+45000000*3=170000000

    (45, 17, 2, 30000000),  -- 2 units of Fujifilm X100V
    (46, 17, 1, 55000000),  -- 1 unit of Panasonic Lumix S5
    -- 30000000*2+55000000=115000000

    (47, 18, 3, 7000000),   -- 3 units of Beats Solo Pro
    (48, 18, 1, 6000000),   -- 1 unit of Bose SoundLink Revolve
    --7000000*3+6000000=27000000

    (49, 19, 2, 2000000),   -- 2 units of Amazon Echo Dot
    (50, 19, 1, 4000000),   -- 1 unit of Google Nest Hub
    --2000000*2+4000000=8000000

    (51, 20, 2, 12000000);  -- 2 units of Apple Watch Series 6
    --12000000*2=24000000
GO